name: TEM-TECH CORNER
'on':
  push:
    branches:
      - main
  pull_request: null
jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: '${{ github.workflow }}-${{ github.ref }}'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: 0.119.0
          extended: true
      - name: Build
        run: hugo --minify
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: '${{ secrets.AWS_ROLE_ARN }}'
          aws-region: '${{ secrets.AWS_REGION }}'
      - name: Sync to S3
        run: |
          aws s3 sync ./public s3://devops1122 --delete --acl public-read
      - name: Invalidate chache
        run: |
           aws cloudfront create-invalidation \
           --distribution-id E8WQLBBBL1WPY \ 
           --paths "/*"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          publish_dir: ./public
permissions:
  id-token: write
  contents: write

